import Head from "next/head";
import Image from "next/image";
import WorkExperience from "./Components/WorkExperience";
import { Container } from "@chakra-ui/react";
import ResponsiveImage from "./Components/ResponsiveImage";
import AboutUs from "./Components/AboutUs";
import Leaders from "./Components/Leaders";
export default function Home() {
  return (
    <>
      <Head>
        <title>Political Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative w-full  lg:h-screen h-60">
          <Image
            src="https://raw.githubusercontent.com/Anandpandey0/portfolio-images/main/main-banner-votebridge.PNG"
            alt="Alt"
            fill
            className="object-fill lg:object-fill"
          />
        </div>
      </main>
      <AboutUs />
      <WorkExperience />

      <Leaders />
    </>
  );
}
