import Head from "next/head";
import HomePage from "./Components/HomePage";
import Header from "./Components/Header";
import AboutUs from "./Components/AboutUs";
import Services from "./Components/Services";
import WhyUs from "./Components/WhyUs";
import AllServices from "./Components/AllServices";
import Footer from "./Components/Footer";

export default function Home() {
  return (
    <div className="overflow-x-hidden w-screen h-screen bg-gray-200">
      <Head>
        <title>Political Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="bg-orange h-[250vh] lg:h-[100vh] bg-cover bg-no-repeat "
        style={{
          backgroundImage:
            'url("https://raw.githubusercontent.com/Anandpandey0/portfolio-images/main/india-gate-mornings-scaled.jpg")',
        }}
      >
        <Header />
        <HomePage />
      </div>
      <Services />
      <AboutUs />
      <WhyUs />
      <AllServices />
      <Footer />
    </div>
  );
}
